const express = require('express')
const cors = require('cors')
const app = express()

app.use(cors())
const port = 3000

app.get('/', (req, res) => {
    res.send('Hello World!')
})


app.post('/auth', (req, res) => {
    res.send({
        accessToken: 'this_is_an_access_token',
        refreshToken: 'this_is_a_refresh_token'
    })
})


app.get('/users', (req, res) => {
    if (!req.headers['authorization'])
        res.status(401).send('Not authorized')
    else res.send(
        [{
            "id": 1,
            "first_name": "Dyan",
            "last_name": "Bullas",
            "email": "dbullas0@1688.com",
            "gender": "Female",
            "ip_address": "189.165.46.5"
        }, {
            "id": 2,
            "first_name": "Tomasina",
            "last_name": "Paulig",
            "email": "tpaulig1@desdev.cn",
            "gender": "Genderfluid",
            "ip_address": "190.98.57.67"
        }, {
            "id": 3,
            "first_name": "Ransell",
            "last_name": "Fleeman",
            "email": "rfleeman2@hhs.gov",
            "gender": "Male",
            "ip_address": "107.136.157.33"
        }, {
            "id": 4,
            "first_name": "Bailey",
            "last_name": "Moy",
            "email": "bmoy3@unblog.fr",
            "gender": "Male",
            "ip_address": "245.70.193.56"
        }, {
            "id": 5,
            "first_name": "Hyacinthia",
            "last_name": "Guiness",
            "email": "hguiness4@ftc.gov",
            "gender": "Female",
            "ip_address": "186.217.203.119"
        }, {
            "id": 6,
            "first_name": "Jarret",
            "last_name": "De Hailes",
            "email": "jdehailes5@reference.com",
            "gender": "Male",
            "ip_address": "0.74.130.55"
        }, {
            "id": 7,
            "first_name": "Kin",
            "last_name": "Rudderham",
            "email": "krudderham6@statcounter.com",
            "gender": "Male",
            "ip_address": "211.42.252.148"
        }, {
            "id": 8,
            "first_name": "Layla",
            "last_name": "Daal",
            "email": "ldaal7@boston.com",
            "gender": "Female",
            "ip_address": "209.88.228.232"
        }, {
            "id": 9,
            "first_name": "Wallace",
            "last_name": "Cohrs",
            "email": "wcohrs8@fda.gov",
            "gender": "Male",
            "ip_address": "154.222.12.136"
        }, {
            "id": 10,
            "first_name": "Vinnie",
            "last_name": "Foyle",
            "email": "vfoyle9@instagram.com",
            "gender": "Female",
            "ip_address": "79.116.152.7"
        }, {
            "id": 11,
            "first_name": "Nadiya",
            "last_name": "Siggins",
            "email": "nsigginsa@cmu.edu",
            "gender": "Female",
            "ip_address": "64.171.114.251"
        }, {
            "id": 12,
            "first_name": "Nancee",
            "last_name": "Kerfod",
            "email": "nkerfodb@cdbaby.com",
            "gender": "Female",
            "ip_address": "244.86.1.50"
        }, {
            "id": 13,
            "first_name": "Kendall",
            "last_name": "Cubbinelli",
            "email": "kcubbinellic@webnode.com",
            "gender": "Male",
            "ip_address": "81.31.250.94"
        }, {
            "id": 14,
            "first_name": "Remus",
            "last_name": "Langmaid",
            "email": "rlangmaidd@whitehouse.gov",
            "gender": "Male",
            "ip_address": "221.140.142.194"
        }, {
            "id": 15,
            "first_name": "Harmony",
            "last_name": "Praton",
            "email": "hpratone@digg.com",
            "gender": "Female",
            "ip_address": "66.213.143.231"
        }, {
            "id": 16,
            "first_name": "Eadie",
            "last_name": "Rusted",
            "email": "erustedf@google.pl",
            "gender": "Female",
            "ip_address": "24.148.41.218"
        }, {
            "id": 17,
            "first_name": "Nanci",
            "last_name": "Scobie",
            "email": "nscobieg@google.pl",
            "gender": "Female",
            "ip_address": "203.168.50.138"
        }, {
            "id": 18,
            "first_name": "Glenn",
            "last_name": "Greve",
            "email": "ggreveh@jiathis.com",
            "gender": "Female",
            "ip_address": "23.26.129.105"
        }, {
            "id": 19,
            "first_name": "Valentijn",
            "last_name": "Coldbathe",
            "email": "vcoldbathei@wordpress.com",
            "gender": "Male",
            "ip_address": "71.120.226.8"
        }, {
            "id": 20,
            "first_name": "Abdul",
            "last_name": "Glanton",
            "email": "aglantonj@rakuten.co.jp",
            "gender": "Male",
            "ip_address": "87.68.46.110"
        }, {
            "id": 21,
            "first_name": "Yolanda",
            "last_name": "Fairtlough",
            "email": "yfairtloughk@jigsy.com",
            "gender": "Female",
            "ip_address": "140.89.171.86"
        }, {
            "id": 22,
            "first_name": "Siobhan",
            "last_name": "Wasiela",
            "email": "swasielal@behance.net",
            "gender": "Female",
            "ip_address": "123.21.62.125"
        }, {
            "id": 23,
            "first_name": "Michele",
            "last_name": "Burgon",
            "email": "mburgonm@imgur.com",
            "gender": "Male",
            "ip_address": "209.199.60.117"
        }, {
            "id": 24,
            "first_name": "Cher",
            "last_name": "Dyhouse",
            "email": "cdyhousen@youku.com",
            "gender": "Female",
            "ip_address": "213.154.224.35"
        }, {
            "id": 25,
            "first_name": "Rosaline",
            "last_name": "Usherwood",
            "email": "rusherwoodo@paypal.com",
            "gender": "Female",
            "ip_address": "249.46.35.244"
        }, {
            "id": 26,
            "first_name": "Koralle",
            "last_name": "Foldes",
            "email": "kfoldesp@businesswire.com",
            "gender": "Female",
            "ip_address": "102.47.94.220"
        }, {
            "id": 27,
            "first_name": "Spence",
            "last_name": "Riby",
            "email": "sribyq@blogspot.com",
            "gender": "Male",
            "ip_address": "87.0.229.55"
        }, {
            "id": 28,
            "first_name": "Mindy",
            "last_name": "Ambrogiotti",
            "email": "mambrogiottir@gnu.org",
            "gender": "Female",
            "ip_address": "103.152.194.8"
        }, {
            "id": 29,
            "first_name": "Abagael",
            "last_name": "Butterley",
            "email": "abutterleys@pcworld.com",
            "gender": "Female",
            "ip_address": "129.130.199.207"
        }, {
            "id": 30,
            "first_name": "Gunther",
            "last_name": "Jeannot",
            "email": "gjeannott@phpbb.com",
            "gender": "Male",
            "ip_address": "70.223.79.22"
        }, {
            "id": 31,
            "first_name": "Alexandros",
            "last_name": "Davidove",
            "email": "adavidoveu@hexun.com",
            "gender": "Male",
            "ip_address": "63.193.245.226"
        }, {
            "id": 32,
            "first_name": "Trudie",
            "last_name": "Wloch",
            "email": "twlochv@acquirethisname.com",
            "gender": "Female",
            "ip_address": "163.134.6.80"
        }, {
            "id": 33,
            "first_name": "Rolf",
            "last_name": "Lapwood",
            "email": "rlapwoodw@tripadvisor.com",
            "gender": "Male",
            "ip_address": "26.50.134.168"
        }, {
            "id": 34,
            "first_name": "Elsy",
            "last_name": "Skala",
            "email": "eskalax@theatlantic.com",
            "gender": "Female",
            "ip_address": "114.182.197.97"
        }, {
            "id": 35,
            "first_name": "Sunshine",
            "last_name": "Goldie",
            "email": "sgoldiey@devhub.com",
            "gender": "Agender",
            "ip_address": "252.108.251.25"
        }, {
            "id": 36,
            "first_name": "Elvera",
            "last_name": "Minico",
            "email": "eminicoz@netscape.com",
            "gender": "Bigender",
            "ip_address": "135.37.131.125"
        }, {
            "id": 37,
            "first_name": "Hamilton",
            "last_name": "Sprott",
            "email": "hsprott10@wp.com",
            "gender": "Male",
            "ip_address": "2.234.188.169"
        }, {
            "id": 38,
            "first_name": "Ewart",
            "last_name": "Jessard",
            "email": "ejessard11@multiply.com",
            "gender": "Male",
            "ip_address": "226.196.238.197"
        }, {
            "id": 39,
            "first_name": "Price",
            "last_name": "Moodie",
            "email": "pmoodie12@wikia.com",
            "gender": "Male",
            "ip_address": "123.53.119.210"
        }, {
            "id": 40,
            "first_name": "Marlow",
            "last_name": "Jenicke",
            "email": "mjenicke13@goo.gl",
            "gender": "Male",
            "ip_address": "127.103.57.32"
        }, {
            "id": 41,
            "first_name": "Denice",
            "last_name": "McCamish",
            "email": "dmccamish14@example.com",
            "gender": "Female",
            "ip_address": "151.170.82.8"
        }, {
            "id": 42,
            "first_name": "Aristotle",
            "last_name": "Dampier",
            "email": "adampier15@homestead.com",
            "gender": "Male",
            "ip_address": "87.174.6.231"
        }, {
            "id": 43,
            "first_name": "Krystle",
            "last_name": "Bigrigg",
            "email": "kbigrigg16@geocities.jp",
            "gender": "Female",
            "ip_address": "203.216.152.50"
        }, {
            "id": 44,
            "first_name": "Burton",
            "last_name": "Broschke",
            "email": "bbroschke17@surveymonkey.com",
            "gender": "Male",
            "ip_address": "160.94.40.122"
        }, {
            "id": 45,
            "first_name": "Jarad",
            "last_name": "Dobel",
            "email": "jdobel18@zimbio.com",
            "gender": "Male",
            "ip_address": "140.172.134.93"
        }, {
            "id": 46,
            "first_name": "Humfried",
            "last_name": "Acton",
            "email": "hacton19@comsenz.com",
            "gender": "Male",
            "ip_address": "105.185.251.144"
        }, {
            "id": 47,
            "first_name": "Humfrid",
            "last_name": "Egar",
            "email": "hegar1a@washington.edu",
            "gender": "Male",
            "ip_address": "37.26.116.161"
        }, {
            "id": 48,
            "first_name": "Liv",
            "last_name": "Twinbrow",
            "email": "ltwinbrow1b@theguardian.com",
            "gender": "Female",
            "ip_address": "147.38.206.44"
        }, {
            "id": 49,
            "first_name": "Prudy",
            "last_name": "Myles",
            "email": "pmyles1c@dailymotion.com",
            "gender": "Female",
            "ip_address": "185.108.238.182"
        }, {
            "id": 50,
            "first_name": "Rudy",
            "last_name": "Jeste",
            "email": "rjeste1d@rakuten.co.jp",
            "gender": "Male",
            "ip_address": "130.78.145.77"
        }, {
            "id": 51,
            "first_name": "Corella",
            "last_name": "Sivewright",
            "email": "csivewright1e@bloglines.com",
            "gender": "Female",
            "ip_address": "43.88.43.8"
        }, {
            "id": 52,
            "first_name": "Renate",
            "last_name": "Bramford",
            "email": "rbramford1f@xrea.com",
            "gender": "Female",
            "ip_address": "19.14.116.39"
        }, {
            "id": 53,
            "first_name": "Aggy",
            "last_name": "Vivian",
            "email": "avivian1g@guardian.co.uk",
            "gender": "Female",
            "ip_address": "180.45.46.66"
        }, {
            "id": 54,
            "first_name": "Sanson",
            "last_name": "Bonny",
            "email": "sbonny1h@bravesites.com",
            "gender": "Polygender",
            "ip_address": "247.106.9.14"
        }, {
            "id": 55,
            "first_name": "Burl",
            "last_name": "Bubear",
            "email": "bbubear1i@reuters.com",
            "gender": "Male",
            "ip_address": "175.19.207.71"
        }, {
            "id": 56,
            "first_name": "Janey",
            "last_name": "Haquin",
            "email": "jhaquin1j@lycos.com",
            "gender": "Female",
            "ip_address": "56.193.34.207"
        }, {
            "id": 57,
            "first_name": "Garey",
            "last_name": "Hedditch",
            "email": "ghedditch1k@networkadvertising.org",
            "gender": "Non-binary",
            "ip_address": "242.238.48.85"
        }, {
            "id": 58,
            "first_name": "Conrado",
            "last_name": "Cordier",
            "email": "ccordier1l@sogou.com",
            "gender": "Male",
            "ip_address": "234.113.106.97"
        }, {
            "id": 59,
            "first_name": "Olimpia",
            "last_name": "Onion",
            "email": "oonion1m@deviantart.com",
            "gender": "Female",
            "ip_address": "197.34.84.168"
        }, {
            "id": 60,
            "first_name": "Tedd",
            "last_name": "Lemerie",
            "email": "tlemerie1n@apple.com",
            "gender": "Male",
            "ip_address": "248.10.5.237"
        }, {
            "id": 61,
            "first_name": "Henderson",
            "last_name": "Gytesham",
            "email": "hgytesham1o@odnoklassniki.ru",
            "gender": "Male",
            "ip_address": "85.35.136.21"
        }, {
            "id": 62,
            "first_name": "Earle",
            "last_name": "Waite",
            "email": "ewaite1p@jalbum.net",
            "gender": "Male",
            "ip_address": "178.130.37.109"
        }, {
            "id": 63,
            "first_name": "Francois",
            "last_name": "Gillhespy",
            "email": "fgillhespy1q@home.pl",
            "gender": "Male",
            "ip_address": "115.65.155.76"
        }, {
            "id": 64,
            "first_name": "Patience",
            "last_name": "Speed",
            "email": "pspeed1r@usnews.com",
            "gender": "Female",
            "ip_address": "99.224.176.95"
        }, {
            "id": 65,
            "first_name": "Itch",
            "last_name": "Dunton",
            "email": "idunton1s@ox.ac.uk",
            "gender": "Male",
            "ip_address": "5.217.144.53"
        }, {
            "id": 66,
            "first_name": "Orella",
            "last_name": "Amis",
            "email": "oamis1t@samsung.com",
            "gender": "Female",
            "ip_address": "154.188.171.254"
        }, {
            "id": 67,
            "first_name": "Shandeigh",
            "last_name": "Strongman",
            "email": "sstrongman1u@example.com",
            "gender": "Female",
            "ip_address": "138.154.48.31"
        }, {
            "id": 68,
            "first_name": "Meir",
            "last_name": "Mixworthy",
            "email": "mmixworthy1v@goo.ne.jp",
            "gender": "Male",
            "ip_address": "75.199.235.45"
        }, {
            "id": 69,
            "first_name": "Raymond",
            "last_name": "Trulock",
            "email": "rtrulock1w@hhs.gov",
            "gender": "Male",
            "ip_address": "42.6.53.168"
        }, {
            "id": 70,
            "first_name": "Arther",
            "last_name": "Cownden",
            "email": "acownden1x@51.la",
            "gender": "Male",
            "ip_address": "65.0.44.45"
        }, {
            "id": 71,
            "first_name": "Joaquin",
            "last_name": "Jochens",
            "email": "jjochens1y@gov.uk",
            "gender": "Male",
            "ip_address": "201.136.255.198"
        }, {
            "id": 72,
            "first_name": "Orly",
            "last_name": "Fozzard",
            "email": "ofozzard1z@histats.com",
            "gender": "Female",
            "ip_address": "79.133.67.121"
        }, {
            "id": 73,
            "first_name": "Celene",
            "last_name": "Pickover",
            "email": "cpickover20@businessweek.com",
            "gender": "Bigender",
            "ip_address": "65.61.15.83"
        }, {
            "id": 74,
            "first_name": "Anstice",
            "last_name": "Aldiss",
            "email": "aaldiss21@washington.edu",
            "gender": "Female",
            "ip_address": "249.69.90.152"
        }, {
            "id": 75,
            "first_name": "Aloysia",
            "last_name": "Clues",
            "email": "aclues22@google.com.au",
            "gender": "Female",
            "ip_address": "198.179.149.28"
        }, {
            "id": 76,
            "first_name": "Gunner",
            "last_name": "Yeoland",
            "email": "gyeoland23@networkadvertising.org",
            "gender": "Male",
            "ip_address": "195.10.197.84"
        }, {
            "id": 77,
            "first_name": "Brien",
            "last_name": "Camacho",
            "email": "bcamacho24@bloglines.com",
            "gender": "Male",
            "ip_address": "140.247.24.150"
        }, {
            "id": 78,
            "first_name": "Curran",
            "last_name": "Saket",
            "email": "csaket25@discovery.com",
            "gender": "Male",
            "ip_address": "55.223.165.211"
        }, {
            "id": 79,
            "first_name": "Lonny",
            "last_name": "Ryde",
            "email": "lryde26@wiley.com",
            "gender": "Bigender",
            "ip_address": "142.237.255.228"
        }, {
            "id": 80,
            "first_name": "Aldridge",
            "last_name": "Maplethorpe",
            "email": "amaplethorpe27@wunderground.com",
            "gender": "Male",
            "ip_address": "211.13.74.179"
        }, {
            "id": 81,
            "first_name": "Ravid",
            "last_name": "Bill",
            "email": "rbill28@delicious.com",
            "gender": "Male",
            "ip_address": "83.184.35.6"
        }, {
            "id": 82,
            "first_name": "Hazel",
            "last_name": "Mulran",
            "email": "hmulran29@feedburner.com",
            "gender": "Male",
            "ip_address": "52.190.12.212"
        }, {
            "id": 83,
            "first_name": "Donnie",
            "last_name": "Linnit",
            "email": "dlinnit2a@adobe.com",
            "gender": "Female",
            "ip_address": "85.136.40.3"
        }, {
            "id": 84,
            "first_name": "Cecilla",
            "last_name": "Aiken",
            "email": "caiken2b@elpais.com",
            "gender": "Female",
            "ip_address": "173.124.47.17"
        }, {
            "id": 85,
            "first_name": "Imogene",
            "last_name": "Keatley",
            "email": "ikeatley2c@friendfeed.com",
            "gender": "Female",
            "ip_address": "93.72.254.42"
        }, {
            "id": 86,
            "first_name": "Fenelia",
            "last_name": "Fransman",
            "email": "ffransman2d@china.com.cn",
            "gender": "Agender",
            "ip_address": "25.126.222.177"
        }, {
            "id": 87,
            "first_name": "Dietrich",
            "last_name": "Paladini",
            "email": "dpaladini2e@bandcamp.com",
            "gender": "Male",
            "ip_address": "113.13.179.152"
        }, {
            "id": 88,
            "first_name": "Guendolen",
            "last_name": "Devoy",
            "email": "gdevoy2f@columbia.edu",
            "gender": "Female",
            "ip_address": "211.135.70.17"
        }, {
            "id": 89,
            "first_name": "Ronda",
            "last_name": "Crawford",
            "email": "rcrawford2g@tiny.cc",
            "gender": "Female",
            "ip_address": "8.155.194.210"
        }, {
            "id": 90,
            "first_name": "Ilyse",
            "last_name": "McKee",
            "email": "imckee2h@issuu.com",
            "gender": "Agender",
            "ip_address": "113.105.31.61"
        }, {
            "id": 91,
            "first_name": "Ardra",
            "last_name": "Tudge",
            "email": "atudge2i@ezinearticles.com",
            "gender": "Genderfluid",
            "ip_address": "241.130.109.197"
        }, {
            "id": 92,
            "first_name": "Quinlan",
            "last_name": "Guidelli",
            "email": "qguidelli2j@seattletimes.com",
            "gender": "Male",
            "ip_address": "42.161.49.134"
        }, {
            "id": 93,
            "first_name": "Nathalie",
            "last_name": "Maggiore",
            "email": "nmaggiore2k@china.com.cn",
            "gender": "Female",
            "ip_address": "155.105.125.143"
        }, {
            "id": 94,
            "first_name": "Jill",
            "last_name": "Hardison",
            "email": "jhardison2l@boston.com",
            "gender": "Female",
            "ip_address": "176.166.5.37"
        }, {
            "id": 95,
            "first_name": "Domini",
            "last_name": "Abramovici",
            "email": "dabramovici2m@forbes.com",
            "gender": "Non-binary",
            "ip_address": "207.59.164.90"
        }, {
            "id": 96,
            "first_name": "Monah",
            "last_name": "Jansa",
            "email": "mjansa2n@linkedin.com",
            "gender": "Female",
            "ip_address": "98.115.210.249"
        }, {
            "id": 97,
            "first_name": "Legra",
            "last_name": "Saur",
            "email": "lsaur2o@forbes.com",
            "gender": "Female",
            "ip_address": "251.124.159.67"
        }, {
            "id": 98,
            "first_name": "Hannis",
            "last_name": "Marskell",
            "email": "hmarskell2p@unesco.org",
            "gender": "Female",
            "ip_address": "239.159.101.223"
        }, {
            "id": 99,
            "first_name": "Wilburt",
            "last_name": "Lynnitt",
            "email": "wlynnitt2q@geocities.com",
            "gender": "Male",
            "ip_address": "55.118.218.87"
        }, {
            "id": 100,
            "first_name": "Ivette",
            "last_name": "Lambillion",
            "email": "ilambillion2r@skype.com",
            "gender": "Female",
            "ip_address": "44.23.208.61"
        }]
    )

})

app.listen(port, () => {
    console.log(`Example app listening on port ${port}`)
})